---
  version: '3.7'

  services:
    nodetest:
      image: bitchess/bitchess-node:latest
      restart: always
      container_name: bitchess-node
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bitchess.entrypoints=websecure"
        - "traefik.http.routers.bitchess.rule=Host(`bit-chess.de`)"
        - "traefik.http.routers.bitchess.tls=true"
        - "traefik.http.routers.bitchess.tls.certresolver=default"

      networks:
        - traefik_proxy
        

  networks:
    traefik_proxy:
      external:
        name: traefik_proxy
    default:
      driver: bridge
