---
version: '3.7'

services:
  traefik:
    image: traefik
    container_name: traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik
      - ./acme/:/acme/
    environment:
      - TZ=Europe/Berlin
    restart: always
    command: --api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.rule=Host(`bitchess.ddns.net`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"

    networks:
      - traefik_proxy
      - default

    ports:
      - "80:80"
      - "443:443"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
