version: '3.1'

services:
  db:
    image: mariadb:10.3
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_Passwort
#Disable Port Forwarding after development
    ports:
      - 3306:3306
####
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
