name: Build and deploy

on:
  push:
    branches:
      - main
      
  pull_request:
jobs:
 build:
   runs-on: self-hosted
   steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Setting DB Connection String
        run: touch .env && echo "${{ secrets.DB_CONNECT }}" >> .env
        
        
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          nocache: true
          context: .
          file: ./Dockerfile
          push: true
          tags: bitchess/bitchess:latest
          
      - name: Delete old docker images (localy)
        run: docker rmi -f bitchess/bitchess:latest
         
      - name: Delete old docker Instances
        run: docker rm -f bitchess
        
      - name: Start Docker-App
        run: docker-compose up -d
        
